name: "Generate SBOM"
on:
  push:
    branches: [main]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git clone https://github.com/facebook/react.git
    - uses: anchore/sbom-action@v0
      with:
        path: ./react
        format: spdx-json
        artifact-name: sbom.spdx.json
    - uses: actions/upload-artifact@v3
      with:
        path: ./react/sbom.spdx.json
