name: "Generate SBOM"
on:
  push:
    branches: [main]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/syft:latest \
            ./ --output spdx-json=./sbom.spdx.json
    - uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: ./sbom.spdx.json
    - uses: advanced-security/spdx-dependency-submission-action@v0.0.1
      with:
        filePath: ./sbom.spdx.json
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/grype:latest \
            sbom:./sbom.spdx.json --output sarif --file=./sarif.json
    - uses: actions/upload-artifact@v3
      with:
        name: sarif
        path: ./sarif.json
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ./sarif.json
        category: my-coolest-stuff-of-the-day
