name: "Generate SBOM"
on:
  push:
    branches: [main]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/syft:latest \
            ./ --output spdx-json=./sbom-spdx.json
    - uses: actions/upload-artifact@v3
      with:
        name: sbom-report
        path: ./sbom-spdx.json
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/grype:latest \
            sbom:./sbom-spdx.json --output json --file=./cve-scan.json
    - uses: actions/upload-artifact@v3
      with:
        name: cve-report
        path: ./cve-scan.json
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}
        aws-region: ${{ vars.AWS_REGION }}
    - run: |
        aws s3 ls
