name: "Generate SBOM"
on:
  push:
    branches: [main]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - id: datetime
      run: echo "value=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "19.x"
    - run: make build
    # Generate SBOM report
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/syft:latest \
            ./ --output spdx-json=./sbom-spdx-${{ steps.datetime.outputs.value }}.json
    - uses: actions/upload-artifact@v3
      with:
        name: sbom-report
        path: ./sbom-spdx-${{ steps.datetime.outputs.value }}.json
    - uses: advanced-security/spdx-dependency-submission-action@v0.0.1
      continue-on-error: true
      with:
        filePath: ./sbom-spdx-${{ steps.datetime.outputs.value }}.json
    # Generate CVE report
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/grype:latest \
            sbom:./sbom-spdx-${{ steps.datetime.outputs.value }}.json --output json --file=./cve-scan-${{ steps.datetime.outputs.value }}.json
    - uses: actions/upload-artifact@v3
      with:
        name: cve-report
        path: ./cve-scan-${{ steps.datetime.outputs.value }}.json
    # Generate CVE report (SARIF)
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/grype:latest \
            sbom:./sbom-spdx-${{ steps.datetime.outputs.value }}.json --output sarif --file=./${{ steps.datetime.outputs.value }}.sarif
    - uses: github/codeql-action/upload-sarif@v2
      continue-on-error: true
      with:
        sarif_file: ./${{ steps.datetime.outputs.value }}.sarif
    # Upload to the central location
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}
        aws-region: ${{ vars.AWS_REGION }}
    - run: |
        aws s3 cp ./sbom-spdx-${{ steps.datetime.outputs.value }}.json s3://github-nhs-england-tools-sbom-example-bucket/sbom-example/
        aws s3 cp ./cve-scan-${{ steps.datetime.outputs.value }}.json s3://github-nhs-england-tools-sbom-example-bucket/sbom-example/
