name: "Generate SBOM"
on:
  push:
    branches: [main]
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - run: echo "DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/syft:latest \
            ./ --output spdx-json=./sbom-spdx-$DATETIME.json
    - uses: actions/upload-artifact@v3
      with:
        name: sbom-report
        path: ./sbom-spdx-$DATETIME.json
    - run: |
        docker run --rm \
          --volume $PWD:/project \
          --workdir /project \
          anchore/grype:latest \
            sbom:./sbom-spdx-$DATETIME.json --output json --file=./cve-scan-$DATETIME.json
    - uses: actions/upload-artifact@v3
      with:
        name: cve-report
        path: ./cve-scan-$DATETIME.json
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE_NAME }}
        aws-region: ${{ vars.AWS_REGION }}
    - run: |
        aws s3 cp ./sbom-spdx-$DATETIME.json s3://github-nhs-england-tools-sbom-example-bucket/sbom-example/
        aws s3 cp ./cve-scan-$DATETIME.json s3://github-nhs-england-tools-sbom-example-bucket/sbom-example/
